version: '3.8'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PASS_CRYPTO_KEY=${PASS_CRYPTO_KEY}
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=docker-reuse
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_REMOVE_CONTAINERS=true
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # backend:
  #   depends_on:
  #     - dynamodb-local
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   image: backend_pass_gen
  #   container_name: backend-pass-gen
  #   ports:
  #    - "8080:8080"
  #   environment:
  #     AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
  #     AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'

  # frontend:
  #   depends_on:
  #     - backend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   image: node:18.12.1-alpine
  #   container_name: app-node
  #   ports:
  #    - "3000:3000"
  #   command:
  #     - "yarn && yarn start"